### ISSUE TITLE
tokenlib calls

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/pyramid_macauth#1]
I don't understand how this can work:

https://github.com/mozilla-services/pyramid_macauth/blob/master/pyramid_macauth/__init__.py#L206

if I use a custom secret in the tokenlib

**Comment by rfk** [comment]
Hmm, you're right, looks like it can't.

For the version used in mozsvc I re-implemented this method to use the per-node-name secrets, since it needed to use other classes from mozsvc anyway:

https://github.com/mozilla-services/mozservices/blob/master/mozsvc/user/__init__.py#L143

I guess it would make sense to add token-secret and related config options directly on this class.

**Comment by tarekziade** [comment]
what could work I guess is a hook, because the secret evolves most of the time, depending on the context.

In my case there's one secret per user

**Comment by tarekziade** [comment]
There should also be a way in tokenlib to parse the token without checking the signature -- because one may want to extract the uid and use it to get back the secret from a DB, to then verify the sig

**Comment by tarekziade** [comment]
errr the hook exists already :)
